
* Revised version

** Referee report
+ Received [2019-05-14 Tue]
  + Didn't do anything for 9 days
+ [2019-05-23 Thu] Working on it at last
+ Summary of points in report that need addressing
  1. [4/4] Define all symbols where they are introduced. In particular
     - [X] R_0, R_pc
     - [X] relative velocity
     - [X] \Xi and \Xi_sh
     - [X] n_\infty and v
       - We have removed all references to n_\infty.  In Paper I we distinguished between the density at large distances, n_\infty, and the density just outside the shock, n. 
  2. [2/2] 
     - [X] Define more carefully \tau and \kappa given that they are not frequency dependent
       + We have written a new appendix that addresses this question in a more rigorous way, where we discuss the relation between these frequency-averaged quantities and the frequency-dependent optical properties of the grains. This allows us to simplify the discussion in the main text.  We also take more care to clearly distinguish between the optical depths for energy and momentum transfer, using tau_P and tau_abs where necessary. 
     - [X] also \varpi and g
       + We now refer to Fig 6 of Paper II for the provenance of these
  3. [1/1] Minor points
     - [X] Give reference for f_UV in sec 4.0

#+begin_quote
Comments to the Author
This is the third instalment in an good series of papers on bow-shocks and related phenomena. This paper focusses on a specific observational diagnostic - namely the [tau, eta_shell] diagram. I found the discussion thought provoking. From Figure 1, it seems that most of the observed bow shocks are wind driven bow shocks, which is
perhaps not a surprise, but the paper does highlight some objects that should be looked at more closely and may be due to related phenomenon (which the paper then goes on to discuss). The discussion of mass-loss rates determinations made for interesting reading too and gave some thought provoking results.

Having said all that, I did find this a rather difficult paper to read, which meant quite a bit of time having to refer back to results in Paper I and II (and then checking whether I understood where those results came from). The small changes in definition of symbols between papers added to my confusion.

Related to this, the paper is a bit light on defining terms where they are first used, which in turn led to quite a bit of chasing through the paper (compounded with there being lots of slightly different R's, h's, eta's, u, Q's, V's and F's and so on).

The paper is worth publishing and I think the general thrust of the discussion is valid. I would like a number of changes to improve the readability. I know these changes are a bit of a pain and they are not very specific and are a bit more general. But I think the paper would benefit from going through and looking at each symbol and making
sure it is defined carefully.

1) My main comment is whether you can define terms where they are first used.  This is especially acute in section 2 - what is R_0, R_pc. The "Relative velocity" of what to what. What is the difference between capital xi_{sh} and capital xi. I had assumed this was just a typo, but then see Section 4.0

Other examples - what is n_\infinity - is it just n.

Use of v_\infinity - not for the wind terminal velocity (a bit confusing as it is the standard symbol for wind terminal velocity). Though I recognise the need for consistency through the papers (as much as possible).

2) As part of this, can you define tau and kappa a bit more closely. These quantities are usually frequency dependent, but here you are using an effective (or averaged) values. There is the footnote in Section 2, but even that had to read closely as to determine whether tau (Paper I) or tau (Paper II) was the larger. Where do the
assumed values of w and g come from for Q_p/Q_abs.

I know what was meant after re-reading it a few times, but the overall effect was confusing (and involved reading parts of Paper I and Paper II to understand what was going on).

Minor points - the values of f_UV in Sect 4.0 - can you provide reference.
#+end_quote

** Using latexdiff to highlight changes

+ Get temp dir with old version
+ I had to check out an old git version to get this since I had stupidly written over it
#+BEGIN_SRC bash :results verbatim
  TMPDIR=/tmp/ms-bsbwdw03-test
  if test -e $TMPDIR; then
      echo "$TMPDIR found and removed"
      rm -fr $TMPDIR
  else
      echo "$TMPDIR not found"
  fi
  mkdir -p $TMPDIR
  cd $TMPDIR
  pwd
  tar xzf $OLDPWD/ms-bsbwdw03-submitted-v1.tar.gz
  ls -lhR
#+END_SRC

#+RESULTS:
#+begin_example
/tmp/ms-bsbwdw03-test found and removed
/tmp/ms-bsbwdw03-test
total 312
-rw-r--r--   1 will  wheel   1.4K Apr 15  2013 aastex-compat.sty
-rw-r--r--   1 will  wheel    15K Mar 30 19:31 app-cloudy-dust-heating.tex
-rw-r--r--   1 will  wheel   6.7K Mar 16 22:23 app-k17-k18.tex
-rw-r--r--   1 will  wheel   4.4K Apr 15  2013 astrojournals.sty
-rw-r--r--   1 will  wheel    23K Mar 30 23:00 bs-bw-dw-03.bbl
-rw-r--r--   1 will  wheel    17K Mar 30 22:52 bs-bw-dw-03.tex
-rw-r--r--   1 will  wheel   2.2K Mar 25 11:44 bs-bw-dw-defs.tex
drwxr-xr-x  15 will  wheel   480B Jun 21 23:16 figs
-rw-r--r--   1 will  wheel    68K Mar 30 22:52 sec-observational-diagnostics.tex

./figs:
total 9736
-rw-r--r--  1 will  wheel   314K Feb 22 22:47 All-sources-eta-tau.pdf
-rw-r--r--  1 will  wheel    75K Mar 21 22:46 H_versus_ell_annotated.pdf
-rw-r--r--  1 will  wheel    21K Mar 30 20:27 K17-tau-comparison.pdf
-rw-r--r--  1 will  wheel    19K Feb 11 16:01 K18-emissivity-vs-U.pdf
-rw-r--r--  1 will  wheel    19K Mar 30 20:29 K18-mdot-Ux8-comparison.pdf
-rw-r--r--  1 will  wheel   126K Mar 30 19:31 K18-mdot-corrected-comparison-R0-edited.pdf
-rw-r--r--  1 will  wheel   417K Mar 27 11:58 Mdot-vs-lum-combo-edited.pdf
-rw-r--r--  1 will  wheel   3.4M Mar 24 18:13 cygnus-bows-midir-combo.pdf
-rw-r--r--  1 will  wheel    30K Mar 30 18:43 grain-T-vs-U.pdf
-rw-r--r--  1 will  wheel    68K Mar 30 18:41 grain-j70-vs-U-edited.pdf
-rw-r--r--  1 will  wheel   206K Mar 30 19:47 mdot_correlations_edited.pdf
-rw-r--r--  1 will  wheel    25K Feb 13 17:59 sed-comparison.pdf
-rw-r--r--  1 will  wheel    20K Mar 23 23:20 xsec-dust-ratd-ism_10.pdf
#+end_example


#+BEGIN_SRC sh :results verbatim
  # Target output directory
  D=$PWD/latexdiff

  # Expand version 2 from the working directory
  cd ../Papers1234
  ln -svf $PWD/figs $D 
  cp -fv aastex-compat.sty $D
  latexpand bs-bw-dw-03.tex \
            --verbose --keep-comments --explain \
            --expand-bbl bs-bw-dw-03.bbl \
            --show-graphics \
            -o $D/ms03-v2-expand.tex

  # Expand version 1 from the tar file (run block below to populate TMPDIR first)
  TMPDIR=/tmp/ms-bsbwdw03-test
  cd $TMPDIR
  latexpand bs-bw-dw-03.tex \
            --verbose --keep-comments --explain \
            --expand-bbl bs-bw-dw-03.bbl \
            --show-graphics \
            -o $D/ms03-v1-expand.tex

#+END_SRC

#+RESULTS:
: /Users/will/Work/Bowshocks/Jorge/bowshock-shape/papers/bs-bw-dw-03-submit/latexdiff/figs -> /Users/will/Work/Bowshocks/Jorge/bowshock-shape/papers/Papers1234/figs
: aastex-compat.sty -> /Users/will/Work/Bowshocks/Jorge/bowshock-shape/papers/bs-bw-dw-03-submit/latexdiff/aastex-compat.sty

#+name: run-latexdiff
#+header: :var FILE_A="ms03-v1-expand.tex"
#+header: :var FILE_B="ms03-v2-expand.tex"
#+header: :var FILE_DIFF="ms03-diff-v1v2.tex"
#+header: :var OPTIONS="--type=CFONT --ignore-warnings --math-markup=off"
#+BEGIN_SRC sh :eval no 
  cd latexdiff
  latexdiff $OPTIONS --verbose $FILE_A $FILE_B > $FILE_DIFF 2> latexdiff.log
  echo $FILE_DIFF
#+END_SRC

Copy wjh-latexdiff-preamble.tex from the Jorge paper folder

#+call: run-latexdiff(OPTIONS="--preamble=wjh-latexdiff-preamble.tex --append-context2cmd='label' --packages=amsmath,hyperref,siunitx --verbose --ignore-warnings --math-markup=1 --allow-spaces") :results output verbatim :eval yes

#+RESULTS:
: ms03-diff-v1v2.tex

#+BEGIN_SRC sh :results silent
cd latexdiff
pdflatex ms03-diff-v1v2
pdflatex ms03-diff-v1v2
#+END_SRC

#+BEGIN_SRC sh :results silent
open latexdiff/ms03-diff-v1v2.pdf
#+END_SRC

This even works with the math markup diffs. 


* Initial version

** Select files
#+name: srcfiles
#+BEGIN_SRC sh
  srcfiles="bs-bw-dw-03.tex sec-observational-diagnostics.tex app-cloudy-dust-heating.tex app-k17-k18.tex bs-bw-dw-defs.tex bs-bw-dw-03.bbl aastex-compat.sty astrojournals.sty"
#+END_SRC

#+BEGIN_SRC sh :noweb yes :results verbatim
cd ../Papers1234
<<srcfiles>>
grep figs/ $srcfiles |grep -v :% |cut -d{ -f2 | cut -d} -f1
#+END_SRC

#+RESULTS:
#+begin_example
figs/All-sources-eta-tau
figs/K17-tau-comparison
figs/Mdot-vs-lum-combo-edited
figs/K18-mdot-Ux8-comparison
figs/xsec-dust-ratd-ism_10
figs/K18-mdot-corrected-comparison-R0-edited
figs/mdot_correlations_edited
figs/H_versus_ell_annotated
figs/cygnus-bows-midir-combo
figs/grain-T-vs-U
figs/grain-j70-vs-U-edited
figs/sed-comparison
#+end_example

#+name: figfiles
#+BEGIN_SRC sh
  figfiles="figs/All-sources-eta-tau.pdf figs/K17-tau-comparison.pdf figs/Mdot-vs-lum-combo-edited.pdf figs/K18-mdot-Ux8-comparison.pdf figs/xsec-dust-ratd-ism_10.pdf figs/K18-mdot-corrected-comparison-R0-edited.pdf figs/mdot_correlations_edited.pdf figs/H_versus_ell_annotated.pdf figs/cygnus-bows-midir-combo.pdf figs/grain-T-vs-U.pdf figs/grain-j70-vs-U-edited.pdf figs/sed-comparison.pdf"
#+END_SRC

** List files and look at sizes
#+BEGIN_SRC sh :noweb yes :results verbatim
  <<srcfiles>>
  <<figfiles>>
  cd ../Papers1234
  ls -lh $srcfiles $figfiles
#+END_SRC

#+RESULTS:
#+begin_example
-rw-rw-r--  1 will  staff   1.4K Apr 15  2013 aastex-compat.sty
-rw-r--r--  1 will  staff    15K Mar 30 19:31 app-cloudy-dust-heating.tex
-rw-r--r--  1 will  staff   6.7K Mar 16 22:23 app-k17-k18.tex
-rw-rw-r--  1 will  staff   4.4K Apr 15  2013 astrojournals.sty
-rw-r--r--  1 will  staff    23K Apr 11 11:11 bs-bw-dw-03.bbl
-rw-r--r--  1 will  staff    18K Apr 11 11:11 bs-bw-dw-03.tex
-rw-r--r--  1 will  staff   2.2K Mar 25 11:44 bs-bw-dw-defs.tex
-rw-r--r--  1 will  staff   314K Feb 22 22:47 figs/All-sources-eta-tau.pdf
-rw-r--r--  1 will  staff    75K Mar 21 22:46 figs/H_versus_ell_annotated.pdf
-rw-r--r--  1 will  staff    21K Mar 30 20:27 figs/K17-tau-comparison.pdf
-rw-r--r--  1 will  staff    19K Mar 30 20:29 figs/K18-mdot-Ux8-comparison.pdf
-rw-r--r--  1 will  staff   126K Mar 30 19:31 figs/K18-mdot-corrected-comparison-R0-edited.pdf
-rw-r--r--  1 will  staff   417K Apr  2 13:12 figs/Mdot-vs-lum-combo-edited.pdf
-rw-r--r--  1 will  staff   3.4M Mar 24 18:13 figs/cygnus-bows-midir-combo.pdf
-rw-r--r--  1 will  staff    30K Mar 30 18:43 figs/grain-T-vs-U.pdf
-rw-r--r--  1 will  staff    68K Mar 30 18:41 figs/grain-j70-vs-U-edited.pdf
-rw-r--r--  1 will  staff   206K Mar 30 19:47 figs/mdot_correlations_edited.pdf
-rw-r--r--  1 will  staff    25K Feb 13 17:59 figs/sed-comparison.pdf
-rw-r--r--  1 will  staff    20K Mar 23 23:20 figs/xsec-dust-ratd-ism_10.pdf
-rw-r--r--  1 will  staff    68K Apr  7 16:43 sec-observational-diagnostics.tex
#+end_example


** Make tar file to submit
#+BEGIN_SRC sh :noweb yes :results verbatim
  <<srcfiles>>
  <<figfiles>>
  cd ../Papers1234
  tar cvzf $OLDPWD/ms-bsbwdw03.tar.gz $srcfiles $figfiles
  cd - 
  ls -lh
#+END_SRC

#+RESULTS:
: /Users/will/Work/Bowshocks/Jorge/bowshock-shape/papers/bs-bw-dw-03-submit
: total 41608
: -rw-r--r--  1 will  staff   7.1K Apr  1 09:31 bs-bw-dw-03-submit.org
: -r--------@ 1 will  staff   5.2M Mar 30 23:41 bsbwdw03-v1-arxiv.pdf
: -r--------@ 1 will  staff   5.1M Mar 30 23:36 bsbwdw03-v1-processed.pdf
: -rw-r--r--@ 1 will  staff   5.0M Mar 30 23:14 ms-bsbwdw03.pdf
: -rw-r--r--  1 will  staff   4.6M Apr 11 11:15 ms-bsbwdw03.tar.gz


** Test compilation in a temp folder
:PROPERTIES:
:ID:       A61B735A-E813-46B2-BC28-56F06C7FD920
:END:

Make folder

#+BEGIN_SRC bash :results verbatim
  TMPDIR=/tmp/ms-bsbwdw03-test
  if test -e $TMPDIR; then
      echo "$TMPDIR found and removed"
      rm -fr $TMPDIR
  else
      echo "$TMPDIR not found"
  fi
  mkdir -p $TMPDIR
  cd $TMPDIR
  pwd
  tar xzf $OLDPWD/ms-bsbwdw03.tar.gz
  ls -lhR
#+END_SRC

#+RESULTS:
#+begin_example
/tmp/ms-bsbwdw03-test not found
/tmp/ms-bsbwdw03-test
total 312
-rw-r--r--   1 will  wheel   1.4K Apr 15  2013 aastex-compat.sty
-rw-r--r--   1 will  wheel    15K Mar 30 19:31 app-cloudy-dust-heating.tex
-rw-r--r--   1 will  wheel   6.7K Mar 16 22:23 app-k17-k18.tex
-rw-r--r--   1 will  wheel   4.4K Apr 15  2013 astrojournals.sty
-rw-r--r--   1 will  wheel    23K Apr 11 11:11 bs-bw-dw-03.bbl
-rw-r--r--   1 will  wheel    18K Apr 11 11:11 bs-bw-dw-03.tex
-rw-r--r--   1 will  wheel   2.2K Mar 25 11:44 bs-bw-dw-defs.tex
drwxr-xr-x  14 will  wheel   448B Jun 21 22:41 figs
-rw-r--r--   1 will  wheel    68K Apr  7 16:43 sec-observational-diagnostics.tex

./figs:
total 9696
-rw-r--r--  1 will  wheel   314K Feb 22 22:47 All-sources-eta-tau.pdf
-rw-r--r--  1 will  wheel    75K Mar 21 22:46 H_versus_ell_annotated.pdf
-rw-r--r--  1 will  wheel    21K Mar 30 20:27 K17-tau-comparison.pdf
-rw-r--r--  1 will  wheel    19K Mar 30 20:29 K18-mdot-Ux8-comparison.pdf
-rw-r--r--  1 will  wheel   126K Mar 30 19:31 K18-mdot-corrected-comparison-R0-edited.pdf
-rw-r--r--  1 will  wheel   417K Apr  2 13:12 Mdot-vs-lum-combo-edited.pdf
-rw-r--r--  1 will  wheel   3.4M Mar 24 18:13 cygnus-bows-midir-combo.pdf
-rw-r--r--  1 will  wheel    30K Mar 30 18:43 grain-T-vs-U.pdf
-rw-r--r--  1 will  wheel    68K Mar 30 18:41 grain-j70-vs-U-edited.pdf
-rw-r--r--  1 will  wheel   206K Mar 30 19:47 mdot_correlations_edited.pdf
-rw-r--r--  1 will  wheel    25K Feb 13 17:59 sed-comparison.pdf
-rw-r--r--  1 will  wheel    20K Mar 23 23:20 xsec-dust-ratd-ism_10.pdf
#+end_example

We don't run bibtex since that will destroy the .bbl file, and we aren't including the .bib file since arxiv does not like it

#+BEGIN_SRC sh
  TMPDIR=/tmp/ms-bsbwdw03-test
  cd $TMPDIR
  pdflatex bs-bw-dw-03
  pdflatex bs-bw-dw-03
  cp bs-bw-dw-03.pdf $OLDPWD/ms-bsbwdw03.pdf
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :results silent
open ms-bsbwdw03.pdf
#+END_SRC

** DONE Upload to MNRAS website
CLOSED: [2019-03-30 Sat 23:38]
Bow shocks, bow waves, and dust waves. III. Diagnostics

#+BEGIN_QUOTE
Stellar bow shocks, bow waves, and dust waves all result from the action of a star's wind and radiation pressure on a stream of dusty plasma that flows past it.  The dust in these bows emits prominently at mid-infrared wavelengths in the range 8 to 60 micron. We propose a novel diagnostic method, the tau-eta diagram, for analyzing these bows, which is based on comparing the fractions of stellar radiative energy and stellar radiative momentum that is trapped by the bow shell.  This diagram allows the discrimination of wind-supported bow shocks, radiation-supported bow waves, and dust waves in which grains decouple from the gas.  For the wind-supported bow shocks, it allows the stellar wind mass-loss rate to be determined.  We critically compare our method with a previous method that has been proposed for determining wind mass-loss rates from bow shock observations. This comparison points to ways in which both methods can be improved and suggests a downward revision by a factor of two with respect to previously reported mass-loss rates.  From a sample of 23 mid-infrared bow-shaped sources, we identify at least 4 strong candidates for radiation-supported bow waves, which need to be confirmed by more detailed studies, but no strong candidates for dust waves.
#+END_QUOTE


** DONE Upload to arxiv
CLOSED: [2019-04-11 Thu 11:04]
